export const UPDATE_FORM_EMAIL = "UPDATE_FORM_EMAIL";
export const UPDATE_FORM_NAME = "UPDATE_FORM_NAME";
export const UPDATE_DEFAULT_FORM = "UPDATE_DEFAULT_FORM";
export const UPDATE_FORM_FRIEND = "UPDATE_FORM_FRIEND";