export const UPDATE_LOGIN_FORM_USERNAME = "UPDATE_LOGIN_FORM_USERNAME";
export const UPDATE_LOGIN_FORM_PASSWORD = "UPDATE_LOGIN_FORM_PASSWORD";
export const UPDATE_LOGIN_FORM_DEFAULT = "UPDATE_LOGIN_FORM_DEFAULT";